version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/api"
    target-branch: "dev"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "python"
      - "api"
    assignees:
      - "prjkhkted"
    commit-message:
      prefix: "[dev] api-deps"
      include: "scope"
    groups:
      api-dev-all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/api"
    target-branch: "wg-dev"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "python"
      - "api"
    assignees:
      - "prjkhkted"
    commit-message:
      prefix: "[wg-dev] api-deps"
      include: "scope"
    groups:
      api-wg-dev-all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/web"
    target-branch: "dev"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "nodejs"
      - "web"
    assignees:
      - "prjkhkted"
    commit-message:
      prefix: "[dev] web-deps"
      include: "scope"
    groups:
      web-dev-all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/web"
    target-branch: "wg-dev"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "nodejs"
      - "web"
    assignees:
      - "prjkhkted"
    commit-message:
      prefix: "[wg-dev] web-deps"
      include: "scope"
    groups:
      web-wg-dev-all-dependencies:
        patterns:
          - "*"

