version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/api"
    target-branch: "qa"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "python"
      - "api"
    commit-message:
      prefix: "[qa] api-deps"
      include: "scope"
    groups:
      api-qa-all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/api"
    target-branch: "wg-develop"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "python"
      - "api"
    commit-message:
      prefix: "[wg-develop] api-deps"
      include: "scope"
    groups:
      api-wg-develop-all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/web"
    target-branch: "qa"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "nodejs"
      - "web"
    commit-message:
      prefix: "[qa] web-deps"
      include: "scope"
    groups:
      web-qa-all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/web"
    target-branch: "wg-develop"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "nodejs"
      - "web"
    commit-message:
      prefix: "[wg-develop] web-deps"
      include: "scope"
    groups:
      web-wg-develop-all-dependencies:
        patterns:
          - "*"

